### ISSUE TITLE
parse-commit-message: Type should be exact match

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [tunnckoCore/opensource#164]
#### Support plan

- _which support plan is this issue covered by?_ (e.g. Community, Sponsor, or
  Enterprise): Community
- _is this issue currently blocking your project?_ (yes/no): Yes
- _is this issue affecting a production system?_ (yes/no): No

#### Context

- _node version_: 14.16.0
- _module version_: 3.2.3
- _environment_ (e.g. node, browser, native): node
- _used with_ (i.e. popular names of modules): https://github.com/semantic-release/semantic-release
- _any other relevant information_: Using this package to add labels to PRs according to the increment of the commit messages.

#### What are you trying to achieve or the steps to reproduce?

I'm using [Semantic Release](https://github.com/semantic-release/semantic-release) to release my code. I'm writing my own GitHub Action to add / remove labels from GitHub PRs so I know what kind of release merging the PR will trigger. The script gets all the commit messages and uses the `parse-commit-message` module to get the increment type.

```js
import { parse, plugins, applyPlugins } from 'parse-commit-message'

console.log(applyPlugins(plugins[1], parse('fixblahblahblah: Fixed a bug'))[0].increment) // Patch
```
Since `fixblahblahblah` stars with `fix`, the `patch` regex matches the type. Ran into this when using `Feature: something` was a `minor` but it didn't do anything with `Semantic Release`.

#### What was the result you got?
`'patch'`

#### What result did you expect?
`false`

**Comment by tunnckoCore** [comment]
Hey, sorry for the late response.

It's not strictly a commit validation library. I built a whole suite around all that and even GitHub (Probot) Bots back then, completely freeing me of Semantic Release. That was the whole purpose - small separate components, following the Conventional Commits spec. Because we had problems with SR.

What can help you with `Feature` is adding `options.caseSensitive: true`. As about the other, you won't have such commit in the first place, if you have good git commit flow (i use `gitcommit`), docs for contrib, or you have commit linting like `commitlint` which have presets too, so you won't end up with wrong messages in git/github.

Thanks for using it. :)

https://github.com/tunnckoCoreLabs/new-release (`@tunnckocore/release` and `@tunnckocore/release-cli`)
https://github.com/standard-release
_(duh... a lot of stuff, organizations and renaming...)

**Comment by tunnckoCore** [comment]
closing cuz it won't be supported (use a tool for commiting proper messages)
